#page title
page_title                                : #Days OnSite - Improving Performance Together         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1514283070                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : # https://apple.co/2GXEewx                # Enter Google Play Store URL.
subscribe_link                            : http://eepurl.com/g0ksrn
presskit_download_link                    : https://drive.google.com/drive/folders/1Ip2ZKzT9S6LLmEd7paelM2bKFkotLYQ0?usp=sharing   # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                     # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").                                                                                      
app_icon                                  : #assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Days OnSite                              # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : #Coming Soon                             # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The best CRA app to keep track of your monitoring visits, research sites and study protocols. Created and maintained by an indie developer who is also a CRA on the field. #Improving performance together. The CRA tool you were waiting for. 

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Binomial Studio Inc.
your_link                                 : https://twitter.com/BinomialStudio
your_city                                 : Canada

email_address                             : contact@daysonsite.app
facebook_username                         :                                           
#instagram_username                        : 
linkedin_username                         : daysonsiteapp
twitter_username                          : DaysOnSiteApp
#github_username                           : 
#youtube_username                          : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Your Visits in One Place
    description                           : Keep track of your visits in one place. Create recurrent visits all at once.
    fontawesome_icon_name                 : clipboard-list
    
  - title                                 : Visit Details at a Glance
    description                           : Is the visit confirmed? Is it a half or full-day visit? Did you send the report? Keep all the details at hand. 
    fontawesome_icon_name                 : calendar-check

  - title                                 : Scheduling at Ease
    description                           : Plan your visits schedule from pre-study to close out and stay on top of your days on site. View a comprehensive list of previous and next visits for all your sites.
    fontawesome_icon_name                 : business-time

  - title                                 : Never Miss a Deadline
    description                           : Stay on top of deadlines and due dates. Based on your own metrics, you will know when a letter or report is due. Check your pending tasks with a list of pending confirmation and follow up letters as well as reports to be submitted.
    fontawesome_icon_name                 : clock

  - title                                 : Conquering Time Zones
    description                           : Your sites are in different time zones? We’ve got you covered. Current time at site is displayed.
    fontawesome_icon_name                 : globe-americas
  
  - title                                 : Sites in One Place
    description                           : All your sites information in one place. Same site different study protocols? Fear not. View the list of protocols each site is participating in.
    fontawesome_icon_name                 : crosshairs
    
  - title                                 : Apple Maps Integration 
    description                           : What is the fastest way to get to your site? Any restaurants nearby? Days OnSite is fully integrated with Apple Maps.
    fontawesome_icon_name                 : map-marked-alt

  - title                                 : Work-related Contacts
    description                           : All your work-related contacts are in a new group separated from the rest. Days OnSite is fully integrated with your Contacts.
    fontawesome_icon_name                 : address-book
    
  - title                                 : Reaching Monthly Metrics
    description                           : Days OnSite displays how many days on site you are scheduling every month. Find out if you are over or under-booked for your next months and take actions accordingly.
    fontawesome_icon_name                 : chart-line

  - title                                 : Be Part of the Future
    description                           : You have a voice on new features and updates. Be part of the development and play a key role in bringing the features that you want to the app. Find out more in the Learn More section.
    fontawesome_icon_name                 : users-cog

  - title                                 : Support a Fellow Colleague
    description                           : Created and maintained by an indie developer who is also a CRA on the field. An app built by a CRA for CRAs all over the world. 
    fontawesome_icon_name                 : hands-helping

  - title                                 : Your Information is Yours
    description                           : We respect your privacy. We do not access your data and never will. Find more in our Privacy Policy.
    fontawesome_icon_name                 : user-shield #people-arrows

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.3                                       # Default 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
