#page title
page_title                                : Days OnSite - Improving Performance Together         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
#presskit_download_link                    : https://daysonsiteapp.github.io/home/    # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Days OnSite                               # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Coming Soon                               # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Improving performance together. The CRA tool you were waiting for. 

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : R4S3CDev
your_link                                 : https://twitter.com/R4S3CDev
your_city                                 : Canada

email_address                             : contact@daysonsite.app
facebook_username                         :                                           
#instagram_username                        : R4S3CDev
#linkedin_username                         : cesarpalma
twitter_username                          : DaysOnSiteApp
#github_username                           : R4S3CDev
#youtube_username                          : github



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Your Visits in One Place
    description                           : Keep track of your visits in one place. Create recurrent visits and avoid the hassle to create them one by one.
    fontawesome_icon_name                 : clipboard-list
    
  - title                                 : Visit Details at a Glance
    description                           : No more wondering if the visit was confirmed or if you already sent the report. Not every visit is equal, half-days, full days, we take that into account when creating a new visit.
    fontawesome_icon_name                 : calendar-check

  - title                                 : Scheduling at Ease
    description                           : You can schedule visits from Pre Study to Close out and stay on top of your days on site. A comprehensive list of previous and next visits per site.
    fontawesome_icon_name                 : business-time

  - title                                 : Never Miss a Deadline
    description                           : Be on top of deadlines and due date calculations. Based on your own metrics you will know when a letter or report is due. Check your pending tasks with a list of pending confirmation and follow up letters as well as reports to be submitted.
    fontawesome_icon_name                 : clock

  - title                                 : Conquering Timezones
    description                           : Your sites are in different timezones? We got you covered. Current time on site is calculated for you. Be on time for your remote contacts.
    fontawesome_icon_name                 : globe-americas
  
  - title                                 : Sites in One Place
    description                           : All your sites information in one place. Same site different study protocols? Fear not. You can easily check in what protocols your sites are participating.
    fontawesome_icon_name                 : hospital-symbol
    
  - title                                 : Apple Maps Integration 
    description                           : What is the fastest way to get to your site? Any restaurant nearby? Days OnSite is fully integrated with Apple Maps in your device.
    fontawesome_icon_name                 : map-marked-alt

  - title                                 : Contacts Separated from the Rest
    description                           : All your work-related contacts are in new group separated from the rest.  Contacts is fully integrated with your Contacts app in your device.
    fontawesome_icon_name                 : address-book

  - title                                 : Assignments Overview
    description                           : A tree view of all your sponsors, study protocols, sites and visits. All of them at a glance.
    fontawesome_icon_name                 : chart-bar
    
  - title                                 : Reaching Monthly Metrics
    description                           : Days OnSite calculates how many days on site are you scheduling monthly. Be informed if you are over or under-booked for your next months and take actions accordingly.
    fontawesome_icon_name                 : chart-line

  - title                                 : Be Part of the Future
    description                           : You have a voice on new features and updates, be part of the development.  Take advantage of that and take part on the process to bring the features that you want to the app. Read more on the Story section.
    fontawesome_icon_name                 : users-cog

  - title                                 : Support a Fellow Colleague
    description                           : Created and maintain by an Indie developer who as well as you is a CRA on the field. Build for a CRA to CRAs all over the world. 
    fontawesome_icon_name                 : hands-helping

  - title                                 : Your information is yours
    description                           : We Respect our privacy  and we don’t access to it and will never do. Read more about our Privacy Policy.
    fontawesome_icon_name                 : user-shield #people-arrows

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
